language: ruby
rvm:
  - 2.3.1
sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql
bundler_args: --without development
script: bundle exec rails db:create db:schema:load db:migrate test
